"""Enterprise Schema Update

Revision ID: 9a75c479e0a1
Revises: 6c0fc550a553
Create Date: 2026-03-14 22:15:56.721986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a75c479e0a1'
down_revision: Union[str, Sequence[str], None] = '6c0fc550a553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cycle', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_appraisals_manager_id', 'employees', ['manager_id'], ['id'])

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('progress')

    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appraisals_manager_id', type_='foreignkey')
        batch_op.drop_column('cycle')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###
