"""Update Appraisal model

Revision ID: 9c5c7e4aa191
Revises: 0d71de81c377
Create Date: 2026-03-14 21:42:02.050756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5c7e4aa191'
down_revision: Union[str, Sequence[str], None] = '0d71de81c377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('review_period')
        batch_op.drop_column('manager_remarks')
        batch_op.drop_column('final_rating')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_rating', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('manager_remarks', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('review_period', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('date')
        batch_op.drop_column('status')
        batch_op.drop_column('comments')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
